USE [AdventureWorks2012]
GO

SELECT ORDERDATE, YEAR(ORDERDATE) AS [ORDER YEAR],
      MONTH(ORDERDATE) AS [ORDER MONTH],
	  DAY(ORDERDATE) AS [ORDER DAY] 
FROM Sales.SalesOrderHeader 
WHERE SalesOrderID in (43659,43714,60621); 