USE AdventureWorks2012;
 GO 



SELECT CustomerID,
       FIRSTNAME + ' ' + LASTNAME AS NAME, C.TERRITORYID,
	   ROW_NUMBER () OVER (PARTITION BY C.TERRITORYID
	   ORDER BY LASTNAME,FIRSTNAME) AS ROW
FROM Sales.Customer AS C
INNER JOIN PERSON.PERSON AS P
ON C.PERSONID=P.BUSINESSENTITYID
