


USE AdventureWorks2012;
 GO 
 SELECT LASTNAME, REPLACE (LASTNAME,'A','Z') AS "REPLACE A",
	REPLACE (LASTNAME,'A','ZZ') AS "REPLACE TWO CHATACTERS",
	REPLACE (LASTNAME,'ab','') AS "REMOVE STRING"
FROM Person.PERSON
WHERE BusinessEntityID IN (293,295,211,297,299,3057,15027); 