USE [AdventureWorks2012]
GO

--SELECT CAST (DATEPART(YYYY,GETDATE()) AS VARCHAR) +'/'
  --    +CAST(DATEPART(MM,GETDATE()) AS VARCHAR) + '/'
	--  +CAST(DATEPART(DD,GETDATE()) AS VARCHAR) AS DATECAST

SELECT CONVERT(VARCHAR,GETDATE(),111) AS DATECONVERT