


USE AdventureWorks2012;
 GO 
 SELECT BusinessEntityID,LASTNAME,MIDDLENAME,
	REPLACE (LASTNAME,'A',MIDDLENAME) AS "REPLACE WITH MIDDLENAME",
	REPLACE (LASTNAME,MIDDLENAME,'A') AS "REPLACE MIDDLENAME"
FROM Person.PERSON
WHERE BusinessEntityID IN (285,293,10314); 