USE [AdventureWorks2012]
GO

SELECT ORDERDATE, DATEPART (YEAR,ORDERDATE) AS [ORDER YEAR],
      DATEPART(MONTH,ORDERDATE) AS [ORDER MONTH],
	  DATEPART(DAY,ORDERDATE) AS [ORDER DAY],
	  DATEPART(WEEKDAY,ORDERDATE) AS [ORDER WEEKDAY]
FROM Sales.SalesOrderHeader 
WHERE SalesOrderID in (43659,43714,60621); 