USE [AdventureWorks2012]
GO

SELECT ORDERDATE, DATENAME (YEAR,ORDERDATE) AS [ORDER YEAR],
      DATENAME(MONTH,ORDERDATE) AS [ORDER MONTH],
	  DATENAME(DAY,ORDERDATE) AS [ORDER DAY],
	  DATENAME(WEEKDAY,ORDERDATE) AS [ORDER WEEKDAY]
FROM Sales.SalesOrderHeader 
WHERE SalesOrderID in (43659,43714,60621); 