USE [AdventureWorks2012]
GO

SELECT ORDERDATE,GETDATE() CURRENTDATETIME,
     DATEDIFF( YEAR,ORDERDATE,GETDATE()) AS YEARDIFF,
	 DATEDIFF( MONTH,ORDERDATE,GETDATE()) AS MONTHDIFF,
	 DATEDIFF( DAY,ORDERDATE,GETDATE()) AS DAYDIFF
FROM Sales.SalesOrderHeader 
WHERE SalesOrderID in (43659,43714,60621); 