USE [AdventureWorks2012]
GO

SELECT ORDERDATE,DATEADD(YEAR,1,ORDERDATE) AS [ONE MORE YEAR],
	DATEADD(MONTH,1,ORDERDATE) AS [ONE MORE MONTH],
	DATEADD(DAY,-1,ORDERDATE) AS [ONE LESS DAY]
FROM Sales.SalesOrderHeader 
WHERE SalesOrderID in (43659,43714,60621); 